name: RegionAPI
version: '1.2.0'
main: com.github.teraprath.region.plugin.RegionPlugin
api-version: '1.20'
authors: [TerryGHG]
website: https://github.com/teraprath
description: A lightweight solution for Regions
softdepend:
  - PlaceholderAPI
commands:
  region:
    description: Admin Command
    permission: region.command
